config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'static_pages' => 'static_pages#home'

  resources :users
  resources :main_page_items

  root 'static_pages#home'

end

app/models/main_page_item.rb
class MainPageItem < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :password, length: {minimum: 6}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_page_items_controller.rb
class MainPageItemsController < ApplicationController
  before_action :set_main_page_item, only: [:show, :edit, :update, :destroy]

  # GET /main_page_items
  # GET /main_page_items.json
  def index
    @main_page_items = MainPageItem.all
  end

  # GET /main_page_items/1
  # GET /main_page_items/1.json
  def show
  end

  # GET /main_page_items/new
  def new
    @main_page_item = MainPageItem.new
  end

  # GET /main_page_items/1/edit
  def edit
  end

  # POST /main_page_items
  # POST /main_page_items.json
  def create
    @main_page_item = MainPageItem.new(main_page_item_params)

    respond_to do |format|
      if @main_page_item.save
        format.html { redirect_to @main_page_item, notice: 'Main page item was successfully created.' }
        format.json { render :show, status: :created, location: @main_page_item }
      else
        format.html { render :new }
        format.json { render json: @main_page_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_page_items/1
  # PATCH/PUT /main_page_items/1.json
  def update
    respond_to do |format|
      if @main_page_item.update(main_page_item_params)
        format.html { redirect_to @main_page_item, notice: 'Main page item was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_page_item }
      else
        format.html { render :edit }
        format.json { render json: @main_page_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_page_items/1
  # DELETE /main_page_items/1.json
  def destroy
    @main_page_item.destroy
    respond_to do |format|
      format.html { redirect_to main_page_items_url, notice: 'Main page item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_page_item
      @main_page_item = MainPageItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_page_item_params
      params.require(:main_page_item).permit(:title, :description, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_items_helper.rb
module MainPageItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <!--<%= link_to "Sampale app", "#", cl: :logo %>-->
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <li><%= link_to 'Signup', signup_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container content">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <div class="debug-dump">
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>

</body>
</html>

app/views/main_page_items/_form.html.erb
<%= form_for(@main_page_item) do |f| %>
  <% if @main_page_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main_page_item.errors.count, "error") %> prohibited this main_page_item from being saved:</h2>

      <ul>
      <% @main_page_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/main_page_items/edit.html.erb
<h1>Editing Main Page Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @main_page_item %> |
<%= link_to 'Back', main_page_items_path %>

app/views/main_page_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Main Page Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @main_page_items.each do |main_page_item| %>
      <tr>
        <td><%= main_page_item.title %></td>
        <td><%= main_page_item.description %></td>
        <td><%= link_to 'Show', main_page_item %></td>
        <td><%= link_to 'Edit', edit_main_page_item_path(main_page_item) %></td>
        <td><%= link_to 'Destroy', main_page_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main page item', new_main_page_item_path %>

app/views/main_page_items/new.html.erb
<h1>New Main Page Item</h1>

<%= render 'form' %>

<%= link_to 'Back', main_page_items_path %>

app/views/main_page_items/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @main_page_item.title %>
</p>

<p>
  <strong>description:</strong>
  <%= @main_page_item.description %>
</p>

<%= link_to 'Edit', edit_main_page_item_path(@main_page_item) %> |
<%= link_to 'Back', main_page_items_path %>

app/views/static_pages/about.html.erb
<% provide :title, 'About'  %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide :title, 'Help'  %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home'  %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
  <!--<strong>Name:</strong>-->
  <!--<%= @user.name %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Email:</strong>-->
  <!--<%= @user.email %>-->
<!--</p>-->
<%= @user.name %>, <%= @user.email %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>